messages:
  usage: "&cUsage: /report <player> <type> <reason>"
  report:
    - "&7Thank you for reporting &#F4C4F3%player%&7. Your report has been submitted."
    - "&cRemember that reporting someone randomly may result in a ban."
  broadcast:
    - "&7[&c&lREP&r&7] &c%player% has been reported for %type%: &r%reason%"
  reload: "&aConfiguration reloaded successfully."

  last-report:
    server:
      - "&7The last report sent by a player is:"
      - "&7Target: &#F4C4F3%target%"
      - "&7Type: &#F4C4F3%type%"
      - "&7Reason: &#F4C4F3%reason%"
      - "&7Time: &#F4C4F3%time%"
    target:
      - "&7The last report sent by &#F4C4F3%player% &7is:"
      - "&7Target: &#F4C4F3%target%"
      - "&7Type: &#F4C4F3%type%"
      - "&7Reason: &#F4C4F3%reason%"
      - "&7Time: &#F4C4F3%time%"

settings:
  webhook: "https://discord.com/api/webhooks/your-webhook-url"

  storage:
    enabled: true

    # Storage types: yaml, sqlite
    TYPE: "sqlite"

    file:
      yaml: "plugins/Reports/reports.yml"
      sqlite: "plugins/Reports/reports.db"
    logs:
      created: "Storage created."
      error-create: "Error while creating storage: %error%"
      error-saving: "Error while saving storage: %error%"

  tabcomplete:
    enabled: true
    cheating:
      - "Macros"
      - "CW"
      - "AutoTotem"
      - "TriggerBot"
      - "AimAssist"
      - "Reach"
    exploiting:
      - "Command abuse"
      - "Glitching"
    harassment: []
    other: []


exempts:
  argument: "&cArgument not found."
  no-reports: "&cNo reports found."
  player: "&cYou must specify a player to report."
  reason: "&cYou must specify a reason to report."
  type: "&cInvalid report type. Valid types are: cheating, exploiting, harassment, other."
